<?php 
echo "<article>"
        . "<div class='page-header'>"
            . "<h1 style='font-size:2em;'>{$article->getTitle()}</h1>"
        . "</div>"
        . "<div>"
            . "{$article->getFullArticle()}
         </div>
            </article>";
?>
<div class="bs-docs-section">
    <div class="well">
<?php
$form->setAttribute('action', $this->url('blog', array('action' => 'comment-add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
    echo '<fieldset><legend>Добавить комментарий</legend>';
        echo '<div id="comment_error"></div>';
        
        $e = $form->get('userEmail');
        $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        echo '<div class="form-group">';
        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formEmail($e)}</div>";
        echo '</div>';
        
        $e = $form->get('comment');
        $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        echo '<div class="form-group">';
        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formTextarea($e)}</div>";
        echo '</div>';
        
        echo "<input type='hidden' value='{$article->getId()}' name='article'>";
echo $this->formRow($form->get('submit'));
echo '</fieldset>';
echo $this->form()->closeTag();
?>
    </div>
</div>

<script>
    $(function(){
        $('form#comment').submit(function(){
            var fData = $('#comment').serialize();
            $.ajax({
                url:'/comment-add/',
                type: 'post',
                dataType: 'json',
                data: fData,
                success: function(data){
                    if(data['success'] === 1){
                        $('#new-comment-email h3').html($('#user_email').val());
                        $('#new-comment-body').html($('#user_comment').val());
                        $('#new-comment').show();
                        
                        $('.bs-docs-section').hide('slow');
                        $('#no-comments').hide();
                    } else {
                        $('#comment_error').html('');
                        for (var key in data){
                            $('#comment_error').append('<span>'+data[key]+'</span>');
                        }
                    }
                }
            });
            return false;
        });
    });
</script>

<?php 
$comments = $article->getComments();

$commentCnt = $comments->count();
if($commentCnt){
    echo "<h3>Комментарии ({$commentCnt})</h3>";
    foreach ($comments as $comment){
        echo "<div class='panel panel-default'>"
        . "<div class='panel-heading'>"
                . "{$comment->getUserEmail()}"
         . "</div>"
         . "<div class='panel-body'>"
                . "{$comment->getComment()}"
         . "</div>"
         . "</div>";
    }
} else {
    echo "<h3 id='no-comments'>Комментариев нет</h3>";
}
?>
<div id="new-comment" class="panel panel-success" style="display: none;">
    <div id="new-comment-email" class="panel-heading"><h3 class="panel-title"></h3></div>
    <div id="new-comment-body" class="panel-body"></div>
</div>