<h1>Категории</h1>
<a href="/admin/category/add/">Добавить</a><br><br>
<?php 
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>'
            . '<button type="button" class="close" data-dismiss="alter" aria-hidden="true">'
            . '&times;'
            . '</button>'
            . '<ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover ">
    <tbody>
        <tr>
            <th>№</th>
            <th>Ключь</th>
            <th>Название</th>
            <th>Действие</th>
        </tr>
        <?php
        foreach ($category as $item) {
            echo "<tr>
                  <td>{$item->getId()}</td>
                  <td>{$item->getCategoryKey()}</td>
                  <td>{$item->getCategoryName()}</td>";
            echo '<td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id' =>$item->getId())).'">Редактировать</a>&nbsp;'
                    . '<a href="'.$this->url('admin/category', array('action' => 'delete', 'id' =>$item->getId())).'"onclick="if (confirm(\'Удалить запись?\')){document.location = this.href;} return false;">Удалить</a></td>';
                    
        }
        ?>
    </tbody>    
</table>