
<?php 
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>'
            . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
            . '&times;'
            . '</button>'
            . '<ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo '<fieldset><legend>Регистрация</legend>';
    echo '<div class="form-group">';
    echo $this->formRow($form->get('usrName'));
    echo '</div>';
    echo '<div class="form-group">';
    echo $this->formRow($form->get('usrEmail'));
    echo '</div>';
    echo '<div class="form-group">';
    echo $this->formRow($form->get('usrPassword'));
    echo '</div>';
    echo '<div class="form-group">';
    echo $this->formRow($form->get('usrPasswordConfirm'));
    echo '</div>';
    
    echo $this->formSubmit($form->get('submit'));
    echo '</fieldset>';
    echo $this->form()->closeTag();
?>