<div class="bs-docs-section">
    <div class="well">
        <?php 
         $form->setAttribute('action', $this->url('admin/comment', array('action'=>'edit', 'id'=>$id)));
         $form ->setAttribute('class', 'form-horizontal');
         $form->prepare();
         
         echo $this->form()->openTag($form);
            echo '<fieldset><legend>Редактировать комментарии</legend>';
            echo '<div id="comment_errors"></div>';
            echo '<div class="form-group">';
            echo '<label class="col-lg-2 control-label">Статья</label>';
            echo "<div class='col-lg-10'>{$comment->getArticle()->getTitle()}</div>";
            echo '</div>';
            
            $e = $form->get('userEmail');
            $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
            echo '<div class="form-group">';
            echo $this->formLabel($e);
            echo "<div class='col-lg-10'>{$this->formEmail($e)}</div>";
            echo '</div>';
            
            $r = $form->get('comment');
            $r->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
            echo '<div class="form-group">';
            echo $this->formLabel($r);
            echo "<div class='col-lg-10'>{$this->formTextarea($r)}</div>";
            echo '</div>';
            
            echo "<input type='hidden' value='{$comment->getId()}' name='id'>";
            
            echo $this->formRow($form->get('submit'));
            echo '</fildset>';
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
