<h1>Комментарии</h1>

<?php 
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>'
            . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
            . '&times;'
            . '</button>'
            . '<ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover ">
    <tbody>
        <tr>
            <th>#</th>
            <th>Статья</th>
            <th>Email</th>
            <th>Комментарий</th>
            <th>Действие</th>  
        </tr>
<?php 
foreach ($comments as $item){
    echo "<tr>"
            . "<td>{$item->getId()}</td>";
      echo  '<td><a href="'.$this->url('blog', array('action' => 'article', 'id' =>$item->getArticle()->getId())).'">';
      echo  $item->getArticle()->getTitle();
      echo  "</a></td>"
            . "<td>{$item->getUserEmail()}</td>"
            . "<td>{$item->getComment()}</td>";
    echo '<td><a href="'.$this->url('admin/comment', array('action' => 'edit', 'id' =>$item->getId())).'">Редактировать</a>&nbsp;'
                    . '<a href="'.$this->url('admin/comment', array('action' => 'delete', 'id' =>$item->getId())).'"onclick="if (confirm(\'Удалить запись?\')){document.location = this.href;} return false;">Удалить</a></td>';
}
?>
    </tbody></table>
<?php 
    echo $this->paginationControl($comments,
                               'Sliding',
                                'pagination_control', array('route' => 'admin/comment'));
?>